package com.mapper.test;

import com.model.test.UserStatus;
import com.model.test.UserStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int countByExample(UserStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int deleteByExample(UserStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int insert(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int insertSelective(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    List<UserStatus> selectByExample(UserStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    UserStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserStatus record, @Param("example") UserStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int updateByExample(@Param("record") UserStatus record, @Param("example") UserStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int updateByPrimaryKeySelective(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status
     *
     * @mbggenerated Wed Aug 01 15:25:12 CST 2018
     */
    int updateByPrimaryKey(UserStatus record);
}