package com.mapper.test;

import com.model.test.ViewUsers;
import com.model.test.ViewUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViewUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    int countByExample(ViewUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    int deleteByExample(ViewUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    int insert(ViewUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    int insertSelective(ViewUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    List<ViewUsers> selectByExample(ViewUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") ViewUsers record, @Param("example") ViewUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_users
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    int updateByExample(@Param("record") ViewUsers record, @Param("example") ViewUsersExample example);
}