package com.model.test;

public class MyUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.obj_json
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    private String objJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.obj_arr
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    private String objArr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.str_arr
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    private String strArr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.obj_json
     *
     * @return the value of users.obj_json
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public String getObjJson() {
        return objJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.obj_json
     *
     * @param objJson the value for users.obj_json
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public void setObjJson(String objJson) {
        this.objJson = objJson == null ? null : objJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.obj_arr
     *
     * @return the value of users.obj_arr
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public String getObjArr() {
        return objArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.obj_arr
     *
     * @param objArr the value for users.obj_arr
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public void setObjArr(String objArr) {
        this.objArr = objArr == null ? null : objArr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.str_arr
     *
     * @return the value of users.str_arr
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public String getStrArr() {
        return strArr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.str_arr
     *
     * @param strArr the value for users.str_arr
     *
     * @mbggenerated Fri Jul 27 16:44:31 CST 2018
     */
    public void setStrArr(String strArr) {
        this.strArr = strArr == null ? null : strArr.trim();
    }
}