package com.model.test;

public class ViewUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_users.user_id
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_users.username
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_users.user_id
     *
     * @return the value of view_users.user_id
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_users.user_id
     *
     * @param userId the value for view_users.user_id
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_users.username
     *
     * @return the value of view_users.username
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_users.username
     *
     * @param username the value for view_users.username
     *
     * @mbggenerated Thu Aug 02 14:28:02 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}